/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminPackage;

import ElectionPackage.DeclareResult;
import HomePagePackage.LogIn;
import ElectionPackage.ElectionCreation;
import ElectionPackage.ElectionDeletion;
/**
 *
 * @author kunal
 */
public class AdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    
    private String userid,admin_name,password;
    public AdminHomePage(String userid,String admin_name,String password) {
        initComponents();
        this.userid=userid;
        this.admin_name=admin_name;
        this.password=password;
        UserIdLabel.setText(userid);
        AdminNameResultLabel.setText(this.admin_name);
    }
    
    public AdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        AdminNameLabel = new javax.swing.JLabel();
        VoterApproveOrRejectButton = new javax.swing.JButton();
        CandidateApproveOrRejectButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        ScheduleElectionButton = new javax.swing.JButton();
        UserIdLabel = new javax.swing.JLabel();
        AdminNameResultLabel = new javax.swing.JLabel();
        TerminateElectionButton = new javax.swing.JButton();
        ImageLabel = new javax.swing.JLabel();
        DeclareResultButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        WelcomeLabel.setText("                                                                             Welcome");

        AdminNameLabel.setText("Admin Name");

        VoterApproveOrRejectButton.setBackground(new java.awt.Color(63, 126, 50));
        VoterApproveOrRejectButton.setText("Approve/Reject Voter Application");
        VoterApproveOrRejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoterApproveOrRejectButtonActionPerformed(evt);
            }
        });

        CandidateApproveOrRejectButton.setText("Approve/Reject Candidate Application");
        CandidateApproveOrRejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidateApproveOrRejectButtonActionPerformed(evt);
            }
        });

        LogOutButton.setBackground(new java.awt.Color(62, 17, 190));
        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        ScheduleElectionButton.setBackground(new java.awt.Color(240, 108, 10));
        ScheduleElectionButton.setText("Schedule Election");
        ScheduleElectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleElectionButtonActionPerformed(evt);
            }
        });

        TerminateElectionButton.setText("Terminate Election");
        TerminateElectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminateElectionButtonActionPerformed(evt);
            }
        });

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroungImage/vote.jpeg"))); // NOI18N

        DeclareResultButton.setText("Declare Result");
        DeclareResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclareResultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScheduleElectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                            .addComponent(TerminateElectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                            .addComponent(VoterApproveOrRejectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                            .addComponent(CandidateApproveOrRejectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                            .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                            .addComponent(AdminNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeclareResultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(91, 91, 91)
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdminNameResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(UserIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(AdminNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AdminNameResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(ScheduleElectionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TerminateElectionButton)
                        .addGap(18, 18, 18)
                        .addComponent(VoterApproveOrRejectButton)
                        .addGap(10, 10, 10)
                        .addComponent(CandidateApproveOrRejectButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(ImageLabel)))
                .addGap(18, 18, 18)
                .addComponent(DeclareResultButton)
                .addGap(27, 27, 27)
                .addComponent(LogOutButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new LogIn("Admin").setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void VoterApproveOrRejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoterApproveOrRejectButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new ApproveOrReject(userid,admin_name,password,"Voter").setVisible(true);
    }//GEN-LAST:event_VoterApproveOrRejectButtonActionPerformed

    private void CandidateApproveOrRejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidateApproveOrRejectButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new ApproveOrReject(userid,admin_name,password,"Candidate").setVisible(true);
    }//GEN-LAST:event_CandidateApproveOrRejectButtonActionPerformed

    private void ScheduleElectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleElectionButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new ElectionCreation(userid,admin_name,password).setVisible(true);
    }//GEN-LAST:event_ScheduleElectionButtonActionPerformed

    private void TerminateElectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminateElectionButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new ElectionDeletion(userid,admin_name,password).setVisible(true);
    }//GEN-LAST:event_TerminateElectionButtonActionPerformed

    private void DeclareResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclareResultButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new DeclareResult(userid,admin_name,password).setVisible(true);
    }//GEN-LAST:event_DeclareResultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminNameLabel;
    private javax.swing.JLabel AdminNameResultLabel;
    private javax.swing.JButton CandidateApproveOrRejectButton;
    private javax.swing.JButton DeclareResultButton;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton ScheduleElectionButton;
    private javax.swing.JButton TerminateElectionButton;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JButton VoterApproveOrRejectButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
