/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomePagePackage;


import java.sql.*;

/**
 *
 * @author kunal
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form VoterRegistration
     */
    private String registration_type,application_id,name,father_spouse_name,age,address,constituency,userid,password,status="PENDING",job_level,party_name;
    public Registration() {
        initComponents();
       
       
    }
    public Registration(String registration_type) {
        initComponents();
        this.registration_type=registration_type;
         WelcomeLabel.setText("Welcome To "+this.registration_type+" Registration Portal");
        switch(registration_type){
            case "Voter":
              Constituency_Party_Job_Label.setText("Constituency");
              break;
            case "Candidate":
              Constituency_Party_Job_Label.setText("Party_Name");
              break;
            case "Admin":
              Constituency_Party_Job_Label.setText("Job Level");
              break;
        }
    }
    
    
    public void sql_database_VoterApplication_insert()
    {
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/ElectionAndVoting";
           Connection connection=DriverManager.getConnection(url,"root","");
           String query="INSERT INTO VoterApplication VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
           PreparedStatement prestat;
           prestat = connection.prepareStatement(query);
           prestat.setString(1, application_id);
           prestat.setString(2, name);
           prestat.setString(3, father_spouse_name);
           prestat.setString(4, age);
           prestat.setString(5, address);
           prestat.setString(6, constituency);
           prestat.setString(7, userid);
           prestat.setString(8, password);
           prestat.setString(9, status);
           prestat.executeUpdate();
           connection.close();
        }
        catch(Exception exception)
        { 
            System.out.println(exception);
        } 
        
    }
    
    public void sql_database_AdminApplication_insert()
    {
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/ElectionAndVoting";
           Connection connection=DriverManager.getConnection(url,"root","");
           String query="INSERT INTO AdminApplication VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
           PreparedStatement prestat;
           prestat = connection.prepareStatement(query);
           prestat.setString(1, application_id);
           prestat.setString(2, name);
           prestat.setString(3, father_spouse_name);
           prestat.setString(4, age);
           prestat.setString(5, address);
           prestat.setString(6, job_level);
           prestat.setString(7, userid);
           prestat.setString(8, password);
           prestat.setString(9, "APPROVED");
           prestat.executeUpdate();
           connection.close();
        }
        catch(Exception exception)
        { 
            System.out.println(exception);
        } 
        
    }
    public void sql_database_CandidateApplication_insert()
    {
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/ElectionAndVoting";
           Connection connection=DriverManager.getConnection(url,"root","");
           String query="INSERT INTO CandidateApplication VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
           PreparedStatement prestat;
           prestat = connection.prepareStatement(query);
           prestat.setString(1, application_id);
           prestat.setString(2, name);
           prestat.setString(3, father_spouse_name);
           prestat.setString(4, age);
           prestat.setString(5, address);
           prestat.setString(6, party_name);
           prestat.setString(7, userid);
           prestat.setString(8, password);
           prestat.setString(9, "PENDING");
           prestat.executeUpdate();
           connection.close();
        }
        catch(Exception exception)
        { 
            System.out.println(exception);
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        VoterNameLabel = new javax.swing.JLabel();
        Father_SpouseLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        Constituency_Party_Job_Label = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UserIdLabel = new javax.swing.JLabel();
        SubmitApplicationButton = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        Father_SpouseNameField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        Constituency_Party_Job_Field = new javax.swing.JTextField();
        UserIdField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeLabel.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        WelcomeLabel.setText("                Welcome To Registration Portal");

        VoterNameLabel.setText("Voter Name");

        Father_SpouseLabel.setText("Father/Spouse Name");

        AgeLabel.setText("Age");

        AddressLabel.setText("Address");

        Constituency_Party_Job_Label.setText("Constituency/Party Name/Job Level");

        PasswordLabel.setText("Password");

        UserIdLabel.setText("UserId");

        SubmitApplicationButton.setBackground(new java.awt.Color(62, 17, 190));
        SubmitApplicationButton.setText("Submit");
        SubmitApplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitApplicationButtonActionPerformed(evt);
            }
        });

        AddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFieldActionPerformed(evt);
            }
        });

        UserIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIdFieldActionPerformed(evt);
            }
        });

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(SubmitApplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Father_SpouseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VoterNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Constituency_Party_Job_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameField)
                            .addComponent(Father_SpouseNameField)
                            .addComponent(AgeField)
                            .addComponent(AddressField)
                            .addComponent(Constituency_Party_Job_Field)
                            .addComponent(UserIdField)
                            .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VoterNameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Father_SpouseLabel)
                    .addComponent(Father_SpouseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLabel)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Constituency_Party_Job_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Constituency_Party_Job_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIdLabel)
                    .addComponent(UserIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordField))
                .addGap(18, 18, 18)
                .addComponent(SubmitApplicationButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void UserIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIdFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void SubmitApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitApplicationButtonActionPerformed
        // TODO add your handling code here:
        switch(registration_type)
        {
               
            case "Voter": 
                name=NameField.getText();
                father_spouse_name=Father_SpouseNameField.getText();
                age=AgeField.getText();
                address=AddressField.getText();
                constituency=Constituency_Party_Job_Field.getText();
                userid=UserIdField.getText();
                password=PasswordField.getText();
                application_id="APP"+userid+age;
                sql_database_VoterApplication_insert();
                dispose();
                new ApplicationConfirmation(application_id,"Voter").setVisible(true);
                break;
                
            case "Candidate": 
                name=NameField.getText();
                father_spouse_name=Father_SpouseNameField.getText();
                age=AgeField.getText();
                address=AddressField.getText();
                party_name=Constituency_Party_Job_Field.getText();
                userid=UserIdField.getText();
                password=PasswordField.getText();
                application_id="APP"+userid+age;
                sql_database_CandidateApplication_insert();
                dispose();
                new ApplicationConfirmation(application_id,"Candidate").setVisible(true);
                break;
                
            case "Admin": 
                name=NameField.getText();
                father_spouse_name=Father_SpouseNameField.getText();
                age=AgeField.getText();
                address=AddressField.getText();
                job_level=Constituency_Party_Job_Field.getText();
                userid=UserIdField.getText();
                password=PasswordField.getText();
                application_id="APP"+userid+age;
                sql_database_AdminApplication_insert();
                dispose();
                new ApplicationConfirmation(application_id,"Admin").setVisible(true);
                break;
        }           
    }//GEN-LAST:event_SubmitApplicationButtonActionPerformed
    
    /**
     *
     * @param args
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField Constituency_Party_Job_Field;
    private javax.swing.JLabel Constituency_Party_Job_Label;
    private javax.swing.JLabel Father_SpouseLabel;
    private javax.swing.JTextField Father_SpouseNameField;
    private javax.swing.JTextField NameField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SubmitApplicationButton;
    private javax.swing.JTextField UserIdField;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JLabel VoterNameLabel;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
