/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VoterPackage;

import HomePagePackage.LogIn;
import HomePagePackage.ApplicationStatus;
import HomePagePackage.Details;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author kunal
 */
public class VoterHomePage extends javax.swing.JFrame {

    /**
     * Creates new form VoterHomePage
     */
    private String userid,voter_name,password,status="PENDING";
    private boolean active_election=false;
    public VoterHomePage(String userid,String voter_name,String password) {
        initComponents();
        this.userid=userid;
        this.voter_name=voter_name;
        this.password=password;
        UserIdLabel.setText(userid);
        VoterNameResultLabel.setText(voter_name);
        
    }
    
    public VoterHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        TrackApplicationButton = new javax.swing.JButton();
        VoterNameLabel = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JButton();
        VoteButton = new javax.swing.JButton();
        PersonalDetailsButton = new javax.swing.JButton();
        VotePermissionLabel = new javax.swing.JLabel();
        UserIdLabel = new javax.swing.JLabel();
        VoterNameResultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeLabel.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        WelcomeLabel.setText("                                    Welcome");

        TrackApplicationButton.setBackground(new java.awt.Color(63, 126, 50));
        TrackApplicationButton.setText("Track Application Status");
        TrackApplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrackApplicationButtonActionPerformed(evt);
            }
        });

        VoterNameLabel.setText("Voter Name");

        LogOutButton.setBackground(new java.awt.Color(62, 17, 190));
        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        VoteButton.setText("Vote");
        VoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteButtonActionPerformed(evt);
            }
        });

        PersonalDetailsButton.setBackground(new java.awt.Color(240, 108, 20));
        PersonalDetailsButton.setText("View Personal Details");
        PersonalDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TrackApplicationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VoterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(VoterNameResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PersonalDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VotePermissionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(184, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoterNameResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(VotePermissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PersonalDetailsButton)
                .addGap(18, 18, 18)
                .addComponent(VoteButton)
                .addGap(28, 28, 28)
                .addComponent(TrackApplicationButton)
                .addGap(18, 18, 18)
                .addComponent(LogOutButton)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void sql_database_getApplication_status_query()
    {
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/ElectionAndVoting";
           Connection connection=DriverManager.getConnection(url,"root","");
           String query="SELECT Status FROM VoterApplication WHERE UserId = "+"'"+userid+"'"+" AND Password = "+"'"+password+"'"+" ; ";
           PreparedStatement prestat;
           prestat = connection.prepareStatement(query);
           ResultSet results;
           results=prestat.executeQuery();  
           while(results.next()){
           status=results.getString("Status");  
           }
           connection.close();
        }
        catch(Exception exception)
        { 
            System.out.println(exception);
        } 
        
    }
    
    private void sql_database_getActiveElection_query()
    {
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/ElectionAndVoting";
           Connection connection=DriverManager.getConnection(url,"root","");
           String query="SELECT ElectionId FROM ElectionSchedule WHERE Constituency IN ( SELECT Constituency FROM VoterApplication WHERE UserId = "+"'"+userid+"'"+" AND Password = "+"'"+password+"'"+" ) ; ";
           PreparedStatement prestat;
           prestat = connection.prepareStatement(query);
           ResultSet results;
           results=prestat.executeQuery();  
           while(results.next()){
             active_election=true;
           }
           connection.close();
        }
        catch(Exception exception)
        { 
            System.out.println(exception);
        } 
        
        
    }
    
    
    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new LogIn("Voter").setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void TrackApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackApplicationButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new ApplicationStatus(userid,voter_name,password,"Voter").setVisible(true);
    }//GEN-LAST:event_TrackApplicationButtonActionPerformed

    private void VoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteButtonActionPerformed
        // TODO add your handling code here:
        sql_database_getApplication_status_query();
        if(status.equals("APPROVED"))
        {
        sql_database_getActiveElection_query();    
        if(!active_election)    
          {
             VotePermissionLabel.setText("There is No Active Election For Your Constituency.");
          }    
        else    
          {
               dispose();
               new VotingPage(userid,voter_name,password).setVisible(true);
          }
        }
        else
        {
            VotePermissionLabel.setText("Your Application isn't Approved.You are Not allowed to vote");
        }
        
        
    }//GEN-LAST:event_VoteButtonActionPerformed

    private void PersonalDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalDetailsButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Details(userid,voter_name,password,"Voter").setVisible(true);
    }//GEN-LAST:event_PersonalDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton PersonalDetailsButton;
    private javax.swing.JButton TrackApplicationButton;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JButton VoteButton;
    private javax.swing.JLabel VotePermissionLabel;
    private javax.swing.JLabel VoterNameLabel;
    private javax.swing.JLabel VoterNameResultLabel;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
