/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CandidatePackage;

import HomePagePackage.LogIn;
import RatingsAndFeedback.RatingAndFeedbackPage;
import HomePagePackage.ApplicationStatus;
import HomePagePackage.Details;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author kunal
 */
public class CandidateHomePage extends javax.swing.JFrame {

    /**
     * Creates new form CandidateHomePage
     */
    private String userid,candidate_name,password,status;
    private boolean allownomination=false;
    public CandidateHomePage(String userid,String candidate_name,String password) {
        initComponents();
        this.userid=userid;
        this.candidate_name=candidate_name;
        this.password=password;
        UserIdLabel.setText(userid);
        CandidateNameResultLabel.setText(this.candidate_name);
        ErrorMessageLabel.setText("");
    }
    
    public CandidateHomePage() {
        initComponents();
    }

    public void sql_database_query_get_CandidateApplication_status()
    {
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/ElectionAndVoting";
           Connection connection=DriverManager.getConnection(url,"root","");
           String query="SELECT Status FROM CandidateApplication WHERE UserId = "+"'"+userid+"'"+" AND Password = "+"'"+password+"'"+" ; ";
           PreparedStatement prestat;
           prestat = connection.prepareStatement(query);
           ResultSet results;
           results=prestat.executeQuery();
           while(results.next()){
           status=results.getString("Status");                           
           if(status.equals("APPROVED"))
           allownomination=true;                               
           }
           connection.close();
        }
        catch(Exception exception)
        { 
            System.out.println(exception);
        } 
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        CandidateNameLabel = new javax.swing.JLabel();
        TrackStatusButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        NominationFilingButton = new javax.swing.JButton();
        RatingsAndFeedbackButton = new javax.swing.JButton();
        ViewDetailsButton = new javax.swing.JButton();
        ErrorMessageLabel = new javax.swing.JLabel();
        CandidateNameResultLabel = new javax.swing.JLabel();
        UserIdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        WelcomeLabel.setText("                                                         Welcome");

        CandidateNameLabel.setText("Candidate Name");

        TrackStatusButton.setBackground(new java.awt.Color(240, 108, 20));
        TrackStatusButton.setText("Track Application Status");
        TrackStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrackStatusButtonActionPerformed(evt);
            }
        });

        LogOutButton.setBackground(new java.awt.Color(62, 17, 190));
        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        NominationFilingButton.setBackground(new java.awt.Color(62, 17, 190));
        NominationFilingButton.setText("Nomination Filing");
        NominationFilingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NominationFilingButtonActionPerformed(evt);
            }
        });

        RatingsAndFeedbackButton.setBackground(new java.awt.Color(240, 108, 10));
        RatingsAndFeedbackButton.setText("View Ratings And Feedback");
        RatingsAndFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingsAndFeedbackButtonActionPerformed(evt);
            }
        });

        ViewDetailsButton.setBackground(new java.awt.Color(63, 126, 50));
        ViewDetailsButton.setText("View Personal Details");
        ViewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CandidateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96)
                                    .addComponent(CandidateNameResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TrackStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NominationFilingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RatingsAndFeedbackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                                .addComponent(ViewDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(UserIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(ErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(UserIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CandidateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CandidateNameResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrackStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NominationFilingButton)
                .addGap(18, 18, 18)
                .addComponent(RatingsAndFeedbackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewDetailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new LogIn("Candidate").setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void TrackStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackStatusButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new ApplicationStatus(userid,candidate_name,password,"Cnadidate").setVisible(true);
    }//GEN-LAST:event_TrackStatusButtonActionPerformed

    private void NominationFilingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NominationFilingButtonActionPerformed
        // TODO add your handling code here:
       sql_database_query_get_CandidateApplication_status();
       if(allownomination)
       {
       dispose();
       new NominationFiling().setVisible(true);
       }
       else
       {
           ErrorMessageLabel.setText("You Application is Not Approved.Hence You can't file Nomination");
       }
    }//GEN-LAST:event_NominationFilingButtonActionPerformed

    private void RatingsAndFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingsAndFeedbackButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       new RatingAndFeedbackPage(userid,candidate_name,password).setVisible(true);
    }//GEN-LAST:event_RatingsAndFeedbackButtonActionPerformed

    private void ViewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Details(userid,candidate_name,password,"Candidate").setVisible(true);
    }//GEN-LAST:event_ViewDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidateHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidateHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidateHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidateHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidateHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidateNameLabel;
    private javax.swing.JLabel CandidateNameResultLabel;
    private javax.swing.JLabel ErrorMessageLabel;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton NominationFilingButton;
    private javax.swing.JButton RatingsAndFeedbackButton;
    private javax.swing.JButton TrackStatusButton;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JButton ViewDetailsButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
